config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :objectives do
    resources :reviews
  end

  root 'objectives#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/objective.rb
require 'csv'

class Objective < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: {minimum: 10}
  validates :deadline, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |objective|
        csv << objective.attributes.values
      end
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :objective

  validates :question, presence: true, length: { minimum: 5 }
  validates :comment, presence: true, length: {minimum: 10}
  validates :confidence_level, numericality: { only_integer: true }
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def set_attachment_name(name)
    escaped = URI.encode(name)
    response.headers['Content-Disposition'] = "attachment; filename*=UTF-8''#{escaped}"
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController

  def index
    @objectives = Objective.all

    respond_to do |format|
      format.html
      format.csv { send_data @objectives.to_csv }
      format.xlsx { set_attachment_name "Objectives #{Time.now.utc.strftime('%A%d%b%Y')}.xlsx" }
    end
  end

  def show
    @objective = Objective.find(params[:id])
    @reviews = @objective.reviews.all
  end

  def new
    @objective = Objective.new
  end

  def edit
    @objective = Objective.find(params[:id])
  end

  def create
    @objective = Objective.new(objective_params)

    if @objective.save
      redirect_to @objective
    else
      render 'new'
    end
  end

  def update
    @objective = Objective.find(params[:id])

    if @objective.update(objective_params)
      redirect_to @objective
    else
      render 'edit'
    end
  end

  def destroy
    @objective = Objective.find(params[:id])
    @objective.destroy

    redirect_to objectives_path
  end

  private

  def objective_params
    params.require(:objective).permit(:title, :description, :deadline)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def index
    @objective = Objective.find(params[:objective_id])
    @reviews = @objective.reviews.all
end

def show
  @objective = Objective.find(params[:objective_id])
  @review = @objective.reviews.find(params[:id])
end

def create
  @objective = Objective.find(params[:objective_id])
  @review = @objective.reviews.create(review_params)
  redirect_to objective_path(@objective)
end

def edit
  @objective = Objective.find(params[:objective_id])
  @review = @objective.reviews.find(params[:id])

end

def destroy
  @objective = Objective.find(params[:objective_id])
  @review = @objective.reviews.find(params[:id])
  @review.destroy

  redirect_to objectives_path(@objective)
end

def update
@objective = Objective.find(params[:objective_id])
 @review = @objective.reviews.find(params[:id])

  if @review.update(review_params)
    redirect_to objectives_path
  else
    render 'edit'
  end
end

private
  def review_params
    params.require(:review).permit(:question, :comment, :confidence_level, :completed)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pdtracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/objectives/edit.html.erb
<p>Edit objective</p>

<%= form_for :objective, url: objective_path, :method => :PUT do |f| %>
  <% if @objective.errors.any? %>
    <div id="form_error">
      <% @objective.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :deadline %>
    <%= f.date_select :deadline %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<p><%= link_to 'Cancel', objectives_path %></p>

app/views/objectives/index.html.erb
<h2>List of current objectives</h2>

<p>
  Download objectives:
  <%= link_to "CSV", objectives_path(format: "csv") %> |
  <%= link_to "Excel", objectives_path(format: "xlsx") %>
</p>

<% @objectives.each do |objective| %>
  <h3><%= objective.title %></h3>
  <p><%= objective.description %></p>
  <p><%= objective.deadline.strftime("%A %d %b %Y") %> (<%= distance_of_time_in_words(objective.deadline, DateTime.now) %> from now)</p>
  <p><%= link_to "Edit", edit_objective_path(objective) %> | <%= link_to "View", objective_path(objective) %> | <%= link_to "Delete", objective_path(objective), method: :delete, data: {confirm: 'Are you sure?'} %>
      </p>
  <hr />
<% end %>

<p><%= link_to 'Add a new objective', new_objective_path %></p>

app/views/objectives/new.html.erb
Add a new objective:

<%= form_for :objective, url: objectives_path do |f| %>
  <% if @objective.errors.any? %>
    <div id="form_error">
      <% @objective.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :deadline %>
    <%= f.date_select :deadline %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<p><%= link_to 'Cancel', objectives_url %></p>

app/views/objectives/show.html.erb
<h2> <%= @objective.title %> </h2>

<p>
  <%= @objective.description %>
</p>

<p>
  <strong>Deadline: </strong>
  <%= @objective.deadline.strftime("%A %d %b %Y") %> (<%= distance_of_time_in_words(@objective.deadline, DateTime.now) %> from now)
</p>
<hr />

<h2>Reviews</h2>
<% @objective.reviews.each do |review| %>
  <p>
    <strong>Title:</strong>
    <%= review.question %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>
  <p>
    <strong>Current confidence level:</strong>
    <%= review.confidence_level %>
  </p>
  <p>
    <strong>Review date:</strong>
    <%= review.created_at.strftime("%A %d %b %Y") %>
  </p>
  <p>
    <%= link_to "Edit review", edit_objective_review_path(@objective, review) %> | <%= link_to "Delete review", objective_review_path(@objective), method: :delete, data: {confirm: 'Are you sure?'} %> [Curently deletes all reviews]
  </p>

  <hr />

<% end %>

<h3>Add a review</h3>

<%= form_for ([@objective, @objective.reviews.build]) do |f| %>
  <p>
    <%= f.label :question, "Title" %><br>
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.check_box :completed %>
    <%= f.label :completed, "I have completed this"  %>
  </p>

  <p>
    Rate your confidence level (1-5)
    <%= f.radio_button :confidence_level, 1 %>
    <%= f.label :confidence_level, "Rookie" %>
    <%= f.radio_button :confidence_level, 2 %>
    <%= f.label :confidence_level, "Not bad" %>
    <%= f.radio_button :confidence_level, 3 %>
    <%= f.label :confidence_level, "Okay" %>
    <%= f.radio_button :confidence_level, 4 %>
    <%= f.label :confidence_level, "Good" %>
    <%= f.radio_button :confidence_level, 5 %>
    <%= f.label :confidence_level, "Great!" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to "Edit", edit_objective_path(@objective) %> | <%= link_to 'Back to index', objectives_path %></p>

app/views/reviews/edit.html.erb
<p>Edit objective</p>

<%= form_for :review, url: objective_review_path, :method => :PUT do |f| %>
  <% if @objective.errors.any? %>
    <div id="form_error">
      <% @objective.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <p>
    <%= f.label :question, "Title" %><br>
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.check_box :completed %>
    <%= f.label :completed, "I have completed this"  %>
  </p>
  <p>
    Rate your confidence level (1-5)
    <%= f.radio_button :confidence_level, 1 %>
    <%= f.label :confidence_level, "Rookie" %>
    <%= f.radio_button :confidence_level, 2 %>
    <%= f.label :confidence_level, "Not bad" %>
    <%= f.radio_button :confidence_level, 3 %>
    <%= f.label :confidence_level, "Okay" %>
    <%= f.radio_button :confidence_level, 4 %>
    <%= f.label :confidence_level, "Good" %>
    <%= f.radio_button :confidence_level, 5 %>
    <%= f.label :confidence_level, "Great!" %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<h2>Review for "<%= @objective.title %>"</h2>



<p><%= link_to "Back to objective", objective_path(@objective) %></p>

app/views/reviews/index.html.erb
Index of all reviews for objective

<h2>Reviews</h2>
<% @reviews.each do |review| %>
  <p>
    <strong>Question:</strong>
    <%= review.question %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>
<% end %>

app/views/reviews/new.html.erb
new review for objective

app/views/reviews/show.html.erb
<p>Edit objective</p>

<%= form_for :review, url: objective_review_path, :method => :PUT do |f| %>
  <% if @objective.errors.any? %>
    <div id="form_error">
      <% @objective.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <p>
    <%= f.label :question, "Title" %><br>
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.check_box :completed %>
    <%= f.label :completed, "I have completed this"  %>
  </p>
  <p>
    Rate your confidence level (1-5)
    <%= f.radio_button :confidence_level, 1 %>
    <%= f.label :confidence_level, "Rookie" %>
    <%= f.radio_button :confidence_level, 2 %>
    <%= f.label :confidence_level, "Not bad" %>
    <%= f.radio_button :confidence_level, 3 %>
    <%= f.label :confidence_level, "Okay" %>
    <%= f.radio_button :confidence_level, 4 %>
    <%= f.label :confidence_level, "Good" %>
    <%= f.radio_button :confidence_level, 5 %>
    <%= f.label :confidence_level, "Great!" %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<h2>Review for "<%= @objective.title %>"</h2>



<p><%= link_to "Back to objective", objective_path(@objective) %></p>

app/views/welcome/index.html.erb
<!-- <h1> Welcome to your personal development tracker</h1> -->
<p>[name]</p>
<p>[role]</p>
<p><%= link_to 'View objectives', objectives_url %></p>